In [7]:
import numpy as np

x_data1 = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
t_data1 = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

x_data=np.array(x_data1)
t_data=np.array(t_data1)
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [14]:
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w,b)

[[0.81322257]
 [0.51493608]
 [0.4957798 ]] [0.75869055]


In [9]:
def loss_func(x,t):
    y=np.dot(x,w)+b
    
    return (np.sum((t-y)**2))/len(x)

In [10]:
## 수치 미분 구현
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    
    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) # f(x+delta_x)

        x[idx]=float(tmp_val)-delta_x
        fx2=f(x) # f(x-delta_x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad


In [11]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [23]:
learning_rate=1e-6

f=lambda x: loss_func(x_data, t_data)

print("Initial error value=", loss_func(x_data, t_data),"\n", "Initial w=", w,"\n", "b=",b,"\n")

for step in range(100000):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step % 400==0:
        print("step=", step, "\n","error value=", loss_func(x_data, t_data),"\n", "w=",w, "\n","b=",b,"\n")

Initial error value= 0.14899836513766307 
 Initial w= [[0.988158  ]
 [0.49396496]
 [0.52128625]] 
 b= [0.77601977] 

step= 0 
 error value= 0.14899835399722342 
 w= [[0.98815805]
 [0.49396498]
 [0.52128617]] 
 b= [0.77601981] 

step= 400 
 error value= 0.1489939019452638 
 w= [[0.98817957]
 [0.49397572]
 [0.52125415]] 
 b= [0.77603312] 

step= 800 
 error value= 0.1489894581041336 
 w= [[0.98820106]
 [0.49398645]
 [0.52122216]] 
 b= [0.77604643] 

step= 1200 
 error value= 0.1489850224578902 
 w= [[0.98822253]
 [0.49399716]
 [0.5211902 ]] 
 b= [0.77605973] 

step= 1600 
 error value= 0.1489805949906599 
 w= [[0.98824398]
 [0.49400787]
 [0.52115827]] 
 b= [0.77607303] 

step= 2000 
 error value= 0.14897617568660732 
 w= [[0.98826541]
 [0.49401856]
 [0.52112638]] 
 b= [0.77608633] 

step= 2400 
 error value= 0.14897176452987912 
 w= [[0.98828682]
 [0.49402925]
 [0.52109451]] 
 b= [0.77609962] 

step= 2800 
 error value= 0.14896736150467652 
 w= [[0.9883082 ]
 [0.49403992]
 [0.52106268]] 