In [45]:
import numpy as np

# x_data=np.array([1,2,3,4,5]).reshape(5,1)
x_data=np.array([[1,1],[2,2],[3,3],[4,4],[5,5]]).reshape(5,2)
t_data=np.array([3,5,7,9,11]).reshape(5,1) #->y=2x+1의 식
print(x_data)
print(t_data)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [46]:
w=np.random.rand(2,1)
b=np.random.rand(1)
w,b

(array([[0.26640848],
        [0.87824552]]),
 array([0.2903915]))

- 비용 함수(Cost function) 또는 손실 함수(Loss function) \
기계 학습에서 모델의 예측값과 실제 관측값(라벨 또는 타겟 값) 사이의 차이를 측정하는 함수


In [47]:
#손실함수 수식
# 평균 제곱 오차(Mean Squared Error, MSE)를 계산 
# MSE는 회귀 문제에서 주로 사용되는 손실 함수로, 모델이 예측한 값과 실제 라벨 간의 차이를 측정하는 데 사용

def loss_func(x,t):
    y=np.dot(x,w)+b
    
    return (np.sum((t-y)**2))/len(x)

#def loss_func(x, t):: 손실 함수 loss_func는 두 개의 인자 x와 t를 받습니다. 여기서 x는 입력 데이터의 배열이고, t는 해당 입력 데이터에 대한 실제 라벨 또는 타겟값의 배열입니다.
# y = np.dot(x, w) + b: 주어진 입력 데이터 x와 가중치 w를 내적하고 편향 b를 더하여 예측값 y를 계산합니다. 이 과정은 선형 회귀 모델의 예측을 나타냅니다.
# (np.sum((t - y)**2)) / len(x): 예측값 y와 실제 라벨 t 간의 평균 제곱 오차(MSE)를 계산합니다.
# 먼저 (t - y)**2를 통해 각 데이터 포인트에서 오차를 제곱합니다. 그런 다음 np.sum을 사용하여 모든 데이터 포인트의 제곱 오차를 더합니다. 최종적으로 len(x)로 나누어 데이터 포인트의 수로 평균을 구합니다.
# 최종적으로 계산된 평균 제곱 오차(MSE)를 반환합니다.



In [48]:
## 수치 미분 구현
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    
    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) # f(x+delta_x)

        x[idx]=float(tmp_val)-delta_x
        fx2=f(x) # f(x-delta_x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad


In [49]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [60]:
learning_rate=1e-2

f=lambda x: loss_func(x_data, t_data)

print("Initial error value=", loss_func(x_data, t_data),"\n", "Initial w=", w,"\n", "b=",b,"\n")

for step in range(20001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step % 400==0:
        print("step=", step, "\n","error value=", loss_func(x_data, t_data),"\n", "w=",w, "\n","b=",b,"\n")

Initial error value= 1.0270968985977573e-28 
 Initial w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 0 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 400 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 800 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 1200 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 1600 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 2000 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 2400 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 2800 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 3200 
 error value= 1.0270968985977573e-28 
 w= [[0.69408148]
 [1.30591852]] 
 b= [1.] 

step= 3600 
 error value= 1.0270968985977573e-28 
 w