In [19]:
import numpy as np

# x_data=np.array([1,2,3,4,5]).reshape(5,1)
x_data=np.array([[1,1],[2,2],[3,3],[4,4],[5,5]]).reshape(5,2)

t_data=np.array([3,5,7,9,11]).reshape(5,1) #->y=2x+1의 식
print(x_data)
print(t_data)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [20]:
w=np.random.rand(1,1)
b=np.random.rand(1)
w,b

(array([[0.63675368]]), array([0.38810093]))

- 비용 함수(Cost function) 또는 손실 함수(Loss function) \
기계 학습에서 모델의 예측값과 실제 관측값(라벨 또는 타겟 값) 사이의 차이를 측정하는 함수


In [21]:
#손실함수 수식
# 평균 제곱 오차(Mean Squared Error, MSE)를 계산 
# MSE는 회귀 문제에서 주로 사용되는 손실 함수로, 모델이 예측한 값과 실제 라벨 간의 차이를 측정하는 데 사용

def loss_func(x,t):
    y=np.dot(x,w)+b
    
    return (np.sum((t-y)**2))/len(x)

#def loss_func(x, t):: 손실 함수 loss_func는 두 개의 인자 x와 t를 받습니다. 여기서 x는 입력 데이터의 배열이고, t는 해당 입력 데이터에 대한 실제 라벨 또는 타겟값의 배열입니다.
# y = np.dot(x, w) + b: 주어진 입력 데이터 x와 가중치 w를 내적하고 편향 b를 더하여 예측값 y를 계산합니다. 이 과정은 선형 회귀 모델의 예측을 나타냅니다.
# (np.sum((t - y)**2)) / len(x): 예측값 y와 실제 라벨 t 간의 평균 제곱 오차(MSE)를 계산합니다.
# 먼저 (t - y)**2를 통해 각 데이터 포인트에서 오차를 제곱합니다. 그런 다음 np.sum을 사용하여 모든 데이터 포인트의 제곱 오차를 더합니다. 최종적으로 len(x)로 나누어 데이터 포인트의 수로 평균을 구합니다.
# 최종적으로 계산된 평균 제곱 오차(MSE)를 반환합니다.



In [22]:
## 수치 미분 구현
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    
    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) # f(x+delta_x)

        x[idx]=float(tmp_val)-delta_x
        fx2=f(x) # f(x-delta_x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad


In [23]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [24]:
learning_rate=1e-2

f=lambda x: loss_func(x_data, t_data)

print("Initial error value=", loss_func(x_data, t_data), "Initial w=", w, "b=",b)

for step in range(20001):
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)

    if step % 400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=",w, "b=",b)

Initial error value= 25.822281341062354 Initial w= [[0.63675368]] b= [0.38810093]
step= 0 error value= 15.197224527676587 w= [[0.97338181]] b= [0.461936]
step= 400 error value= 0.0010338044811080277 w= [[2.0208793]] b= [0.92463755]
step= 800 error value= 6.596283771860724e-05 w= [[2.00527408]] b= [0.98096357]


step= 1200 error value= 4.2088190169459e-06 w= [[2.00133222]] b= [0.99519143]
step= 1600 error value= 2.6854753570467605e-07 w= [[2.00033652]] b= [0.99878536]
step= 2000 error value= 1.713492042350072e-08 w= [[2.000085]] b= [0.99969318]
step= 2400 error value= 1.0933092241924825e-09 w= [[2.00002147]] b= [0.9999225]
step= 2800 error value= 6.975959211092618e-11 w= [[2.00000542]] b= [0.99998042]
step= 3200 error value= 4.451074391344692e-12 w= [[2.00000137]] b= [0.99999505]
step= 3600 error value= 2.8400486043372805e-13 w= [[2.00000035]] b= [0.99999875]
step= 4000 error value= 1.8121189021562948e-14 w= [[2.00000009]] b= [0.99999968]
step= 4400 error value= 1.156238955977447e-15 w= [[2.00000002]] b= [0.99999992]
step= 4800 error value= 7.377487700092139e-17 w= [[2.00000001]] b= [0.99999998]
step= 5200 error value= 4.707270288560162e-18 w= [[2.]] b= [0.99999999]
step= 5600 error value= 3.0035131641329324e-19 w= [[2.]] b= [1.]
step= 6000 error value= 1.9164028826260333e-20 w= [[2.]] b= [1.]

In [25]:
predict(np.array([10,20]))

ValueError: shapes (2,) and (1,1) not aligned: 2 (dim 0) != 1 (dim 0)