In [57]:
import torch
import torch.optim as optim

torch.manual_seed(1)

In [58]:
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data = torch.FloatTensor([[3],[5],[7],[9],[11]])


- 가중치(w)
    - 가중치는 입력 데이터와 곱해져서 모델의 예측값을 계산하는 데 사용됩니다.\
     입력과 가중치의 곱은 데이터의 특성(feature)을 나타내며, 이러한 가중치들은 모델이 데이터를 학습하는 과정에서 조정됩니다. \
     가중치는 모델이 입력 데이터의 각 특성을 얼마나 중요하게 생각하는지를 결정하며, 학습을 통해 최적화되는 값입니다.\
     예를 들어, 선형 회귀 모델에서 가중치는 각 입력 특성과 곱해져서 출력을 만듭니다. \
     만약 입력 데이터가 (x1, x2)이고 가중치가 (w1, w2)라면, 모델의 출력은 y = w1x1 + w2x2와 같이 계산됩니다. \
     가중치 w1과 w2는 학습 과정에서 입력 데이터에 가장 적합한 값을 찾게 됩니다\\

- 편향(b)
    - 편향은 모델이 입력 데이터를 얼마나 잘 처리하는지를 나타내는 상수 값입니다. \
       가중치와 달리 입력 데이터와 직접 곱해지지 않고, 각 뉴런(또는 출력)에 더해집니다. \
       편향은 모델이 학습 데이터의 평균을 중심으로 예측을 수행할 수 있도록 도와줍니다.\
       선형 회귀에서 편향은 모델의 예측값에 상수 값을 더해줍니다. \
       예를 들어, y = w1x1 + w2x2 + b와 같이 편향 b가 더해집니다. 편향은 학습을 통해 데이터의 평균과 가까운 값을 가지도록 최적화됩니다.

In [59]:
w=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
print(w,b)

tensor([0.], requires_grad=True) tensor([0.], requires_grad=True)


In [60]:
y=x_data*w+b

In [61]:
cost=torch.mean((t_data-y)**2)
print(cost)

tensor(57., grad_fn=<MeanBackward0>)


In [62]:
#경사하강법으로 w,b업데이트를 하기위한 최적화하는식
optimizer=optim.SGD([w,b], lr=0.01)  #GD =Gradient Disecent 통계적 

In [64]:
nb_epochs = 2000    #2000번 훈련할거다
for epoch in range(nb_epochs+1): #+1하는이유 = 그래야 2000번째것이 나오니깐
    
    #비용 함수(cost)는 모델의 예측값(y)과 실제 라벨(t_data) 간의 차이를 측정    
    y=x_data*w+b #y=예측값 
    cost=torch.mean((y-t_data)**2)#cost = 비용함수

    optimizer.zero_grad()  #gradient를 초기화하는것
    cost.backward() #비용함수 계산
    optimizer.step()  #w,b업데이트

    if epoch % 100==0:
        print('EPOCH {:4d} w:{:.3f}, b:{:.3f} Cost:{:.6f}'\
                .format(epoch, w.item(), b.item(), cost.item()))



EPOCH    0 w:2.000, b:1.000 Cost:0.000000
EPOCH  100 w:2.000, b:1.000 Cost:0.000000
EPOCH  200 w:2.000, b:1.000 Cost:0.000000
EPOCH  300 w:2.000, b:1.000 Cost:0.000000
EPOCH  400 w:2.000, b:1.000 Cost:0.000000
EPOCH  500 w:2.000, b:1.000 Cost:0.000000
EPOCH  600 w:2.000, b:1.000 Cost:0.000000
EPOCH  700 w:2.000, b:1.000 Cost:0.000000
EPOCH  800 w:2.000, b:1.000 Cost:0.000000
EPOCH  900 w:2.000, b:1.000 Cost:0.000000
EPOCH 1000 w:2.000, b:1.000 Cost:0.000000
EPOCH 1100 w:2.000, b:1.000 Cost:0.000000
EPOCH 1200 w:2.000, b:1.000 Cost:0.000000
EPOCH 1300 w:2.000, b:1.000 Cost:0.000000
EPOCH 1400 w:2.000, b:1.000 Cost:0.000000
EPOCH 1500 w:2.000, b:1.000 Cost:0.000000
EPOCH 1600 w:2.000, b:1.000 Cost:0.000000
EPOCH 1700 w:2.000, b:1.000 Cost:0.000000
EPOCH 1800 w:2.000, b:1.000 Cost:0.000000
EPOCH 1900 w:2.000, b:1.000 Cost:0.000000
EPOCH 2000 w:2.000, b:1.000 Cost:0.000000


In [70]:
import numpy as np

x_data =torch.FloatTensor( [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]])
t_data = y_train = torch.FloatTensor([[152.],[185.],[180.],[196.],[142.]])

print(x_data)
print(t_data)

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [73]:
w= torch.zeros((3,1), requires_grad=True)
b= torch.zeros(1, requires_grad=True)

y= x_data.matmul(w)+b

In [78]:
optimizer= optim.SGD([w,b], lr=1e-6)
nb_epochs= 2000

for epoch in range(nb_epochs+1): #+1하는이유 = 그래야 2000번째것이 나오니깐

    y=x_data.matmul(w)+b #y=예측값 
    cost=torch.mean((y-t_data)**2) #cost = 비용함수

    optimizer.zero_grad()  #gradient를 초기화하는것
    cost.backward() #비용함수 계산
    optimizer.step()  #w,b업데이트

    if epoch % 100==0:
        print('EPOCH {:4d}/{}, y:{}, w:{:.3f}, b:{:.3f} Cost:{:.6f}'\
                .format(epoch, nb_epochs, y.squeeze().detach(), cost.item(), w.item(), b.item()))




NameError: name 'matmul' is not defined