In [83]:
import torch
import torch.optim as optim

torch.manual_seed(1)

In [84]:
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data = torch.FloatTensor([[3],[5],[7],[9],[11]])


- 가중치(w)
    - 가중치는 입력 데이터와 곱해져서 모델의 예측값을 계산하는 데 사용됩니다.\
     입력과 가중치의 곱은 데이터의 특성(feature)을 나타내며, 이러한 가중치들은 모델이 데이터를 학습하는 과정에서 조정됩니다. \
     가중치는 모델이 입력 데이터의 각 특성을 얼마나 중요하게 생각하는지를 결정하며, 학습을 통해 최적화되는 값입니다.\
     예를 들어, 선형 회귀 모델에서 가중치는 각 입력 특성과 곱해져서 출력을 만듭니다. \
     만약 입력 데이터가 (x1, x2)이고 가중치가 (w1, w2)라면, 모델의 출력은 y = w1x1 + w2x2와 같이 계산됩니다. \
     가중치 w1과 w2는 학습 과정에서 입력 데이터에 가장 적합한 값을 찾게 됩니다\\

- 편향(b)
    - 편향은 모델이 입력 데이터를 얼마나 잘 처리하는지를 나타내는 상수 값입니다. \
       가중치와 달리 입력 데이터와 직접 곱해지지 않고, 각 뉴런(또는 출력)에 더해집니다. \
       편향은 모델이 학습 데이터의 평균을 중심으로 예측을 수행할 수 있도록 도와줍니다.\
       선형 회귀에서 편향은 모델의 예측값에 상수 값을 더해줍니다. \
       예를 들어, y = w1x1 + w2x2 + b와 같이 편향 b가 더해집니다. 편향은 학습을 통해 데이터의 평균과 가까운 값을 가지도록 최적화됩니다.

In [85]:
w=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
print(w,b)

tensor([0.], requires_grad=True) tensor([0.], requires_grad=True)


In [86]:
y=x_data*w+b

In [87]:
cost=torch.mean((t_data-y)**2)
print(cost)

tensor(57., grad_fn=<MeanBackward0>)


In [88]:
#경사하강법으로 w,b업데이트를 하기위한 최적화하는식
optimizer=optim.SGD([w,b], lr=0.01)  #GD =Gradient Disecent 통계적 

In [89]:
nb_epochs = 2000    #2000번 훈련할거다
for epoch in range(nb_epochs+1): #+1하는이유 = 그래야 2000번째것이 나오니깐
    
    #비용 함수(cost)는 모델의 예측값(y)과 실제 라벨(t_data) 간의 차이를 측정    
    y=x_data*w+b #y=예측값 
    cost=torch.mean((y-t_data)**2)#cost = 비용함수

    optimizer.zero_grad()  #gradient를 초기화하는것
    cost.backward() #비용함수 계산
    optimizer.step()  #w,b업데이트

    if epoch % 100==0:
        print('EPOCH {:4d} w:{:.3f}, b:{:.3f} Cost:{:.6f}'\
                .format(epoch, w.item(), b.item(), cost.item()))



EPOCH    0 w:0.500, b:0.140 Cost:57.000000
EPOCH  100 w:2.082, b:0.706 Cost:0.015866
EPOCH  200 w:2.058, b:0.790 Cost:0.008060
EPOCH  300 w:2.041, b:0.851 Cost:0.004094
EPOCH  400 w:2.030, b:0.893 Cost:0.002080


EPOCH  500 w:2.021, b:0.924 Cost:0.001056
EPOCH  600 w:2.015, b:0.946 Cost:0.000537
EPOCH  700 w:2.011, b:0.961 Cost:0.000273
EPOCH  800 w:2.008, b:0.973 Cost:0.000138
EPOCH  900 w:2.005, b:0.980 Cost:0.000070
EPOCH 1000 w:2.004, b:0.986 Cost:0.000036
EPOCH 1100 w:2.003, b:0.990 Cost:0.000018
EPOCH 1200 w:2.002, b:0.993 Cost:0.000009
EPOCH 1300 w:2.001, b:0.995 Cost:0.000005
EPOCH 1400 w:2.001, b:0.996 Cost:0.000002
EPOCH 1500 w:2.001, b:0.997 Cost:0.000001
EPOCH 1600 w:2.001, b:0.998 Cost:0.000001
EPOCH 1700 w:2.000, b:0.999 Cost:0.000000
EPOCH 1800 w:2.000, b:0.999 Cost:0.000000
EPOCH 1900 w:2.000, b:0.999 Cost:0.000000
EPOCH 2000 w:2.000, b:1.000 Cost:0.000000


In [90]:
import numpy as np

x_data =torch.FloatTensor( [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]])
t_data = y_train = torch.FloatTensor([[152.],[185.],[180.],[196.],[142.]])

print(x_data)
print(t_data)

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [91]:
w= torch.zeros((3,1), requires_grad=True)
b= torch.zeros(1, requires_grad=True)

y= x_data.matmul(w)+b

In [110]:
optimizer= optim.SGD([w,b], lr=1e-6)
nb_epochs= 2000

for epoch in range(nb_epochs+1): #+1하는이유 = 그래야 2000번째것이 나오니깐

    y=x_data.matmul(w)+b #y=예측값 
    cost=torch.mean((y-t_data)**2) #cost = 비용함수

    optimizer.zero_grad()  #gradient를 초기화하는것
    cost.backward() #비용함수 계산
    optimizer.step()  #w,b업데이트

    if epoch % 100==0:
        print('EPOCH {:4d}/{}, Hypothesis:{}, Cost:{:.6f}'\
                .format(epoch, nb_epochs, y.squeeze().detach(), cost.item()))




EPOCH    0/2000, Hypothesis:tensor([151.8199, 184.3557, 180.6764, 196.7939, 141.0506]), Cost:0.487348
EPOCH  100/2000, Hypothesis:tensor([151.8183, 184.3568, 180.6759, 196.7934, 141.0522]), Cost:0.486287
EPOCH  200/2000, Hypothesis:tensor([151.8167, 184.3580, 180.6755, 196.7929, 141.0538]), Cost:0.485228
EPOCH  300/2000, Hypothesis:tensor([151.8152, 184.3591, 180.6750, 196.7924, 141.0554]), Cost:0.484174
EPOCH  400/2000, Hypothesis:tensor([151.8136, 184.3602, 180.6746, 196.7919, 141.0570]), Cost:0.483116
EPOCH  500/2000, Hypothesis:tensor([151.8120, 184.3613, 180.6741, 196.7913, 141.0586]), Cost:0.482055
EPOCH  600/2000, Hypothesis:tensor([151.8104, 184.3623, 180.6736, 196.7908, 141.0602]), Cost:0.481011
EPOCH  700/2000, Hypothesis:tensor([151.8088, 184.3634, 180.6731, 196.7903, 141.0617]), Cost:0.479965
EPOCH  800/2000, Hypothesis:tensor([151.8072, 184.3645, 180.6727, 196.7897, 141.0633]), Cost:0.478934
EPOCH  900/2000, Hypothesis:tensor([151.8057, 184.3655, 180.6722, 196.7892, 141.06