In [41]:
import torch
import torch.optim as optim

torch.manual_seed(1)

In [42]:
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data = torch.FloatTensor([[3],[5],[7],[9],[11]])


- 가중치(w)
    - 가중치는 입력 데이터와 곱해져서 모델의 예측값을 계산하는 데 사용됩니다.\
     입력과 가중치의 곱은 데이터의 특성(feature)을 나타내며, 이러한 가중치들은 모델이 데이터를 학습하는 과정에서 조정됩니다. \
     가중치는 모델이 입력 데이터의 각 특성을 얼마나 중요하게 생각하는지를 결정하며, 학습을 통해 최적화되는 값입니다.\
     예를 들어, 선형 회귀 모델에서 가중치는 각 입력 특성과 곱해져서 출력을 만듭니다. \
     만약 입력 데이터가 (x1, x2)이고 가중치가 (w1, w2)라면, 모델의 출력은 y = w1x1 + w2x2와 같이 계산됩니다. \
     가중치 w1과 w2는 학습 과정에서 입력 데이터에 가장 적합한 값을 찾게 됩니다\\

- 편향(b)
    - 편향은 모델이 입력 데이터를 얼마나 잘 처리하는지를 나타내는 상수 값입니다. \
       가중치와 달리 입력 데이터와 직접 곱해지지 않고, 각 뉴런(또는 출력)에 더해집니다. \
       편향은 모델이 학습 데이터의 평균을 중심으로 예측을 수행할 수 있도록 도와줍니다.\
       선형 회귀에서 편향은 모델의 예측값에 상수 값을 더해줍니다. \
       예를 들어, y = w1x1 + w2x2 + b와 같이 편향 b가 더해집니다. 편향은 학습을 통해 데이터의 평균과 가까운 값을 가지도록 최적화됩니다.

In [43]:
w=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)
print(w,b)

tensor([0.], requires_grad=True) tensor([0.], requires_grad=True)


In [44]:
y=x_data*w+b

In [45]:
cost=torch.mean((t_data-y)**2)
print(cost)

tensor(57., grad_fn=<MeanBackward0>)


In [46]:
#경사하강법으로 w,b업데이트를 하기위한 최적화하는식
optimizer=optim.SGD([w,b], lr=0.01)  #GD =Gradient Disecent 통계적 

In [47]:
nb_epochs = 2000    #2000번 훈련할거다
for epoch in range(nb_epochs+1): #+1하는이유 = 그래야 2000번째것이 나오니깐
    
    #비용 함수(cost)는 모델의 예측값(y)과 실제 라벨(t_data) 간의 차이를 측정    
    y=x_data*w+b #y=예측값 
    cost=torch.mean((y-t_data)**2)#cost = 비용함수

    optimizer.zero_grad()  #gradient를 초기화하는것
    cost.backward() #비용함수 계산
    optimizer.step()  #w,b업데이트

    if epoch % 100==0:
        print('EPOCH {:4d} w:{:.3f}, b:{:.3f} Cost:{:.6f} Hypothesis:{}'\
                .format(epoch, w.item(), b.item(), cost.item(), y.squeeze().detach()))



EPOCH    0 w:0.500, b:0.140 Cost:57.000000 Hypothesis:tensor([0., 0., 0., 0., 0.])
EPOCH  100 w:2.082, b:0.706 Cost:0.015866 Hypothesis:tensor([ 2.7865,  4.8683,  6.9501,  9.0319, 11.1136])
EPOCH  200 w:2.058, b:0.790 Cost:0.008060 Hypothesis:tensor([ 2.8479,  4.9061,  6.9644,  9.0227, 11.0810])
EPOCH  300 w:2.041, b:0.851 Cost:0.004094 Hypothesis:tensor([ 2.8916,  4.9331,  6.9746,  9.0162, 11.0577])
EPOCH  400 w:2.030, b:0.893 Cost:0.002080 Hypothesis:tensor([ 2.9227,  4.9523,  6.9819,  9.0115, 11.0411])


EPOCH  500 w:2.021, b:0.924 Cost:0.001056 Hypothesis:tensor([ 2.9449,  4.9660,  6.9871,  9.0082, 11.0293])
EPOCH  600 w:2.015, b:0.946 Cost:0.000537 Hypothesis:tensor([ 2.9607,  4.9758,  6.9908,  9.0059, 11.0209])
EPOCH  700 w:2.011, b:0.961 Cost:0.000273 Hypothesis:tensor([ 2.9720,  4.9827,  6.9935,  9.0042, 11.0149])
EPOCH  800 w:2.008, b:0.973 Cost:0.000138 Hypothesis:tensor([ 2.9801,  4.9877,  6.9953,  9.0030, 11.0106])
EPOCH  900 w:2.005, b:0.980 Cost:0.000070 Hypothesis:tensor([ 2.9858,  4.9912,  6.9967,  9.0021, 11.0076])
EPOCH 1000 w:2.004, b:0.986 Cost:0.000036 Hypothesis:tensor([ 2.9899,  4.9938,  6.9976,  9.0015, 11.0054])
EPOCH 1100 w:2.003, b:0.990 Cost:0.000018 Hypothesis:tensor([ 2.9928,  4.9955,  6.9983,  9.0011, 11.0038])
EPOCH 1200 w:2.002, b:0.993 Cost:0.000009 Hypothesis:tensor([ 2.9949,  4.9968,  6.9988,  9.0008, 11.0027])
EPOCH 1300 w:2.001, b:0.995 Cost:0.000005 Hypothesis:tensor([ 2.9963,  4.9977,  6.9991,  9.0005, 11.0020])
EPOCH 1400 w:2.001, b:0.996 Cost:0.00

In [48]:
import numpy as np

x_data =torch.FloatTensor( [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]])
t_data = y_train = torch.FloatTensor([[152.],[185.],[180.],[196.],[142.]])

print(x_data)
print(t_data)

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [50]:
W= torch.zeros((3,1), requires_grad=True)
b= torch.zeros(1, requires_grad=True)

y= x_data.matmul(W)+b

In [59]:
optimizer= optim.SGD([W,b], lr=1e-6)
nb_epochs= 2000

for epoch in range(nb_epochs+1): #+1하는이유 = 그래야 2000번째것이 나오니깐

    y=x_data.matmul(W)+b #y=예측값 
    cost=torch.mean((y-t_data)**2) #cost = 비용함수

    optimizer.zero_grad()  #gradient를 초기화하는것
    cost.backward() #비용함수 계산
    optimizer.step()  #w,b업데이트
    print('Epoch:', epoch, '\n', 'Hypothesis:', y, '\n' ,'Cost:', cost.item(), '\n', 'W:', W, '\n', 'b:',b.item())

    # if epoch % 100==0:
    #     print('EPOCH {:4d}/{}, Hypothesis:{}, Cost:{:.6f}'\
    #             .format(epoch, nb_epochs, y.squeeze().detach(), cost.item()))




Epoch: 0 
 Hypothesis: tensor([[152.3668],
        [183.9763],
        [180.8384],
        [196.9546],
        [140.5159]], grad_fn=<AddBackward0>) 
 Cost: 0.9998589754104614 
 W: tensor([[0.7265],
        [0.6034],
        [0.6807]], requires_grad=True) 
 b: 0.009511060081422329
Epoch: 1 
 Hypothesis: tensor([[152.3668],
        [183.9763],
        [180.8384],
        [196.9546],
        [140.5159]], grad_fn=<AddBackward0>) 
 Cost: 0.9998301267623901 
 W: tensor([[0.7265],
        [0.6034],
        [0.6807]], requires_grad=True) 
 b: 0.009511198848485947
Epoch: 2 
 Hypothesis: tensor([[152.3668],
        [183.9764],
        [180.8384],
        [196.9545],
        [140.5159]], grad_fn=<AddBackward0>) 
 Cost: 0.9997782707214355 
 W: tensor([[0.7265],
        [0.6034],
        [0.6807]], requires_grad=True) 
 b: 0.009511337615549564
Epoch: 3 
 Hypothesis: tensor([[152.3667],
        [183.9764],
        [180.8384],
        [196.9546],
        [140.5160]], grad_fn=<AddBackward0>) 
 Cost: 0