소프트맥스 회귀
 - 3개이상의 선택지로부터 1개를 선택하는 문제(다중클래스 분류)를 풀기 위한 방법 <br>
 - 대충 몇번째 선택지의 확률을 출력할거를 선택해서 확인하는 방법이라고 생각하면 됨
 

In [59]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


In [60]:
z= torch.FloatTensor([1,2,3])
y_hat = F.softmax(z,dim=0)
print(y_hat)
#softmax사용시 한행의 것을 다 합해진것의 결과값은 항상 1
print(y_hat.sum())


tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [61]:
z=torch.rand(3,5, requires_grad=True) #<- 3행 5열로 랜덤하게 작성
y_hat = F.softmax(z, dim=1)
print(y_hat)
#마찬가지로 한 행의 것을 다 합해진것의 결과값은 항상 1
print(y_hat.sum())

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)
tensor(3.0000, grad_fn=<SumBackward0>)


In [62]:
y= torch.randint(5, (3,)).long()
print(y)
y_one_hot = torch.zeros_like(y_hat)
y_one_hot.scatter_(1, y.unsqueeze(1),1) #1의 위치가 어디인지 알려주는 것 / 1행의 1의 위치 (3)에 위치 / 2행의 1의 위치 (2)에 위치
print(y_one_hot)

tensor([0, 2, 1])
tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])


In [63]:
print(y.unsqueeze(1))

tensor([[0],
        [2],
        [1]])


In [64]:
torch.manual_seed(1)

In [65]:
x_data=[[1,2,1,1],
        [2,1,3,2],
        [3,1,3,4],
        [4,1,5,5],
        [1,7,5,5],
        [1,2,5,6],
        [1,6,6,6],
        [1,7,7,7]]

y_data=[2,2,2,1,1,1,0,0]
x_train=torch.FloatTensor(x_data)
y_train=torch.LongTensor(y_data)
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [66]:
y_one_hot = torch.zeros(8,3)
y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [70]:
W=torch.zeros((4,3), requires_grad=True)
b=torch.zeros((1,3), requires_grad=True)
optimizer=optim.SGD([W, b], lr=0.1)

In [79]:
n_epochs=10001
for epoch in range(n_epochs):
    y_hat=F.softmax(x_train.matmul(W)+b, dim=1)
    cost=(y_one_hot * -torch.log(y_hat)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print('Epoch:', epoch, 'Cost:', cost.item())

Epoch: 0 Cost: 0.013590933755040169
Epoch: 100 Cost: 0.013546119444072247
Epoch: 200 Cost: 0.01350156869739294
Epoch: 300 Cost: 0.013457324355840683
Epoch: 400 Cost: 0.013413340784609318
Epoch: 500 Cost: 0.013369837775826454
Epoch: 600 Cost: 0.013326437212526798
Epoch: 700 Cost: 0.013283301144838333
Epoch: 800 Cost: 0.013240483589470387
Epoch: 900 Cost: 0.013197975233197212
Epoch: 1000 Cost: 0.013155785389244556
Epoch: 1100 Cost: 0.013113697990775108
Epoch: 1200 Cost: 0.0130719980224967
Epoch: 1300 Cost: 0.013030502945184708
Epoch: 1400 Cost: 0.012989364564418793
Epoch: 1500 Cost: 0.012948342598974705
Epoch: 1600 Cost: 0.012907678261399269
Epoch: 1700 Cost: 0.012867278419435024
Epoch: 1800 Cost: 0.012827099300920963
Epoch: 1900 Cost: 0.012787171639502048
Epoch: 2000 Cost: 0.012747473083436489
Epoch: 2100 Cost: 0.012708034366369247
Epoch: 2200 Cost: 0.012668789364397526
Epoch: 2300 Cost: 0.012629956007003784
Epoch: 2400 Cost: 0.012591155245900154
Epoch: 2500 Cost: 0.012552649714052677
E

In [80]:
model=nn.Linear(4,3)
optimizer = optim.SGD(model.parameters(), lr=0.1)
n_epochs=10000

In [81]:
for epoch in range(n_epochs):
    y_hat=model(x_train)
    cost = F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch: ', epoch, 'Cost: ', cost.item())

Epoch:  0 Cost:  1.6167852878570557
Epoch:  100 Cost:  0.6588909029960632
Epoch:  200 Cost:  0.5734433531761169
Epoch:  300 Cost:  0.5181514024734497
Epoch:  400 Cost:  0.47326549887657166
Epoch:  500 Cost:  0.43351614475250244
Epoch:  600 Cost:  0.3965628445148468
Epoch:  700 Cost:  0.36091411113739014
Epoch:  800 Cost:  0.3253922164440155
Epoch:  900 Cost:  0.28917866945266724
Epoch:  1000 Cost:  0.25414782762527466
Epoch:  1100 Cost:  0.23497340083122253
Epoch:  1200 Cost:  0.2234925776720047
Epoch:  1300 Cost:  0.21305306255817413
Epoch:  1400 Cost:  0.2035093903541565
Epoch:  1500 Cost:  0.1947512924671173
Epoch:  1600 Cost:  0.18668682873249054
Epoch:  1700 Cost:  0.17923787236213684
Epoch:  1800 Cost:  0.17233796417713165
Epoch:  1900 Cost:  0.1659296303987503
Epoch:  2000 Cost:  0.15996326506137848
Epoch:  2100 Cost:  0.15439580380916595
Epoch:  2200 Cost:  0.1491893082857132
Epoch:  2300 Cost:  0.14431050419807434
Epoch:  2400 Cost:  0.13973000645637512
Epoch:  2500 Cost:  0.1

In [83]:
prodiction = model(x_train)
print(prodiction)

tensor([[-11.4186,  -0.1089,  11.8237],
        [ -4.3004,   0.4548,   4.3716],
        [-18.3864,   8.3331,  11.4630],
        [-12.6069,   8.7536,   5.5109],
        [  0.9640,   3.5058,  -2.2738],
        [  4.2153,   7.4299,  -9.0252],
        [  7.0719,   4.7319,  -9.1731],
        [ 10.5022,   5.6714, -13.0725]], grad_fn=<AddmmBackward0>)


In [85]:
class SoftmaxClassModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(4,3)

    def forward(self, x):
        return self.linear(x)

In [87]:
model=SoftmaxClassModel()
optimizer=optim.SGD(model.parameters(), lr=0.1)
n_epochs = 10000

In [89]:
for epoch in range(n_epochs):
    y_hat=model(x_train)
    cost = F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch: ', epoch, 'Cost: ', cost.item())

Epoch:  0 Cost:  0.03986532986164093
Epoch:  100 Cost:  0.03948763385415077
Epoch:  200 Cost:  0.03911696374416351
Epoch:  300 Cost:  0.03875299543142319
Epoch:  400 Cost:  0.03839582949876785
Epoch:  500 Cost:  0.03804491087794304
Epoch:  600 Cost:  0.03770039230585098
Epoch:  700 Cost:  0.03736207261681557
Epoch:  800 Cost:  0.03702965006232262
Epoch:  900 Cost:  0.03670310601592064
Epoch:  1000 Cost:  0.036382146179676056
Epoch:  1100 Cost:  0.036066632717847824
Epoch:  1200 Cost:  0.03575662150979042
Epoch:  1300 Cost:  0.03545163944363594
Epoch:  1400 Cost:  0.03515198454260826
Epoch:  1500 Cost:  0.03485720232129097
Epoch:  1600 Cost:  0.034567270427942276
Epoch:  1700 Cost:  0.034282136708498
Epoch:  1800 Cost:  0.034001536667346954
Epoch:  1900 Cost:  0.0337255522608757
Epoch:  2000 Cost:  0.033453915268182755
Epoch:  2100 Cost:  0.033186543732881546
Epoch:  2200 Cost:  0.03292344510555267
Epoch:  2300 Cost:  0.03266439959406853
Epoch:  2400 Cost:  0.03240932151675224
Epoch:  2

In [92]:
prediction = model(x_train)
print(prediction)

tensor([[-13.8228,  -0.0551,  14.3841],
        [ -3.9516,   0.7393,   5.3643],
        [-22.6757,   9.6895,  13.5155],
        [-14.5503,  10.3340,   6.3924],
        [  0.8633,   4.0958,  -2.4126],
        [  4.5460,   8.4308, -11.1844],
        [  8.4633,   5.4709, -10.8792],
        [ 12.5713,   6.5461, -15.5526]], grad_fn=<AddmmBackward0>)
