- 배열(array): 데이터를 효율적으로 저장하고 다루기 위해 사용.\
 NumPy를 사용하여 배열을 생성하고, 배열 간의 연산이나 슬라이싱과 같은 다양한 작업을 수행할 수 있음.

- 텐서(Tensor): 주로 머신러닝과 딥러닝에서 데이터를 다루기 위해 사용.\
 딥러닝 모델은 주로 텐서를 입력으로 받고, 텐서를 출력으로 내보냄.\
  딥러닝 라이브러리인 파이토치와 텐서플로는 텐서를 생성하고, 뉴럴 네트워크의 학습과 예측 과정에서 텐서를 다루는 기능을 제공.

In [150]:
import torch

In [151]:
torch.tensor([[1,2], [3,4]])

tensor([[1, 2],
        [3, 4]])

In [152]:
x=torch.FloatTensor([[1,2,3], [4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [153]:
print(torch.tensor([[1,2,],[3,4]]))
# print(torch.tensor([[1,2,],[3,4]]), device="cuda:0") #cuda tenser만드는것
print(torch.tensor([[1,2,],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [154]:
ft=torch.FloatTensor([[1,2,],[3,4]])
lt=torch.LongTensor([[1,2],[3,4]])
bt=torch.ByteTensor([[1,2],[3,4]]) #8bit로 작성되었단 결과가 나옴
print(ft)
print(lt)
print(bt)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [155]:
#nparray
import numpy as np

x=np.arange(0,9).reshape(3,3)
print(x, type(x))
x

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [156]:
#array->torch로 변환
tx=torch.from_numpy(x)
print(tx)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)


In [157]:
#torch->nparray
nx=tx.numpy()
print(nx, type(nx))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [158]:
tx #<- long형인데  float형으로, float형인데 long형으로
ft=tx.float()
print(ft)
lt= ft.long()
print(lt)
bt=ft.byte()
print(bt)


tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.uint8)


In [159]:
na=np.arange(1,13).reshape(2,3,2) #(z, y, x축)
na

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [160]:
t=torch.from_numpy(na)

In [161]:
print(t.size())  # 텐서의 크기를 출력합니다.

print(t.shape)  # 텐서의 모양(shape)을 튜플 형태로 출력합니다.

print(t.size(0))  # 텐서의 첫 번째 차원의 크기를 출력합니다.

print(t.shape[2])  # 텐서의 세 번째 차원의 크기를 출력합니다.

print(t.dim())  # 텐서의 차원 수를 출력합니다.

print(len(t.shape))  # 텐서의 차원 수를 출력합니다. t.dim()과 동일한 결과입니다.

print(t.size(-1))  # 텐서의 마지막 차원의 크기를 출력합니다.

print(t.shape[-1])  # 텐서의 마지막 차원의 크기를 출력합니다. t.size(-1)과 동일한 결과입니다.

torch.Size([2, 3, 2])
torch.Size([2, 3, 2])
2
2
3
3
2
2


In [162]:
a = torch.Tensor([[1, 2], [3, 4]])  # 2x2 크기의 텐서 a를 생성합니다.
b = torch.Tensor([[1, 2], [3, 4]])  # 2x2 크기의 텐서 b를 생성합니다.

print(a + b)  # 행렬 덧셈: 텐서 a와 b의 요소를 더하여 결과를 출력합니다.
print(a - b)  # 행렬 뺄셈: 텐서 a와 b의 요소를 빼서 결과를 출력합니다.
print(a * b)  # 요소별 곱셈: 텐서 a와 b의 요소를 곱하여 결과를 출력합니다.
print(a / b)  # 요소별 나눗셈: 텐서 a와 b의 요소를 나누어 결과를 출력합니다.
print(a == b)  # 요소별 비교 (같음): 텐서 a와 b의 요소가 같은지 비교하여 True 또는 False를 출력합니다.
print(a != b)  # 요소별 비교 (다름): 텐서 a와 b의 요소가 다른지 비교하여 True 또는 False를 출력합니다.
print(a ** b)  # 요소별 거듭제곱: 텐서 a의 요소를 텐서 b의 요소만큼 제곱하여 결과를 출력합니다.


tensor([[2., 4.],
        [6., 8.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[True, True],
        [True, True]])
tensor([[False, False],
        [False, False]])
tensor([[  1.,   4.],
        [ 27., 256.]])


In [163]:
print(a+1)
print(a-3)
print(a*2)
print(a/2)
print(a//2)  #// 연산자는 파이썬에서 사용되는 정수 나눗셈(나누기 연산의 몫을 계산)을 수행하는 연산자
print(a==2)
print(a>2)
print(a!=2)

tensor([[2., 3.],
        [4., 5.]])
tensor([[-2., -1.],
        [ 0.,  1.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[0., 1.],
        [1., 2.]])
tensor([[False,  True],
        [False, False]])
tensor([[False, False],
        [ True,  True]])
tensor([[ True, False],
        [ True,  True]])


In [164]:
c=torch.tensor([1,2])
print(a)
print(c)
print(a+c)


tensor([[1., 2.],
        [3., 4.]])
tensor([1, 2])
tensor([[2., 4.],
        [4., 6.]])


In [165]:
print(a)
print(b)
print(a*b) #<- 같은 행 열의 자리의값들끼리 곱함
print(a)
print(a.mul_(b)) # (= print(a*b)과 같은 기능이지만, a의 값이 변해버림
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


In [166]:
print(a)
print(a.sum())
print(a.sum(dim=0)) #열끼리 더하기
print(a.sum(dim=1)) #행끼리 더하기

tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor(30.)
tensor([10., 20.])
tensor([ 5., 25.])


In [167]:
t = np.arange(1, 13).reshape(3, 2, 2)  # 1부터 12까지의 숫자를 3x2x2 크기의 다차원 배열로 생성합니다. # (z, y, x축) 순서로 다차원 배열이 구성됩니다.
t = torch.from_numpy(t)  # NumPy 배열을 파이토치 텐서로 변환합니다.

print(t)  # 3차원 텐서를 출력합니다.
print(t.sum(dim=0))  # 첫 번째 축(z 축)을 따라 텐서의 합을 계산합니다.
print(t.sum(dim=1))  # 두 번째 축(y 축)을 따라 텐서의 합을 계산합니다.
print(t.sum(dim=2))  # 세 번째 축(x 축)을 따라 텐서의 합을 계산합니다.
print(t.sum(dim=-1))  # 마지막 축(x 축)을 따라 텐서의 합을 계산합니다.

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[15, 18],
        [21, 24]])
tensor([[ 4,  6],
        [12, 14],
        [20, 22]])
tensor([[ 3,  7],
        [11, 15],
        [19, 23]])
tensor([[ 3,  7],
        [11, 15],
        [19, 23]])


In [168]:
t=t.float()
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=2))
print(t.mean(dim=-1))



tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor(6.5000)
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])


In [169]:
a=np.arange(12).reshape(2,3,2)
b=np.arange(2,14).reshape(2,3,2)
c=np.arange(1,7).reshape(3,2)

#원래의 NumPy 배열이 변경되지 않기를 원한다면 torch.tensor(a)를 사용하여 새로운 텐서를 생성하는 방법을 선택해야 합니다.
# 이렇게 하면 NumPy 배열과 텐서가 독립적인 메모리를 사용하므로 한쪽의 변경이 다른 쪽에 영향을 주지 않습니다.
d=torch.tensor(a) #값이 바뀌지는 않음
d=torch.from_numpy(a) #값이 바뀜

print(a+b,"\n\n",c)

print(d)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]] 

 [[1 2]
 [3 4]
 [5 6]]
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]], dtype=torch.int32)


In [170]:
x=torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [171]:
print(x.view(3,4),"\n")
print(x.reshape(3,4),"\n")
print(x.view(4,3),"\n")
print(x.view(2,3,2),"\n")
print(x.view(-1,2,3))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]]) 

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [172]:
x=torch.arange(1,13)
x1=x.view(1,2,3,2)
x1

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]])

In [173]:
#squeeze()-> 1차원인 것들을 제거
#unsqueeze() ->1차원을 추가하는것

# x1= x1.unsqueeze(1)
x1
x1= x1.squeeze(1)
x1

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]])

In [174]:
x2=x.view(2,3,2)
x2

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [175]:

x2=x.view(2,3,2)
print(x2)
x2
#x[a,b] -> a=z축의 순서/ b=해당 차원의 행순서
print(x2[1,1]) #2번째 z축의 2번째 행



tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])
tensor([ 9, 10])


In [176]:
x=torch.FloatTensor(4,10)
splits.x.split(3,dim=1)
for s in splits:
    print(x.size())

NameError: name 'splits' is not defined

In [ ]:
x=torch.arange(1,13).view(3,2,2)
print(x)
index=torch.LongTensor([0,1])



y=x.index_select(dim=1, index=index)
y

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])


tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [ ]:
x= torch.FloatTensor([[1,2,3], [4,5,6], [7,8,9]])
y= torch.FloatTensor([[10,11,12], [13,14,15], [16,17,18]])
x,y

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]))

In [ ]:
z=torch.cat([x,y], dim=0)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [ ]:
z=torch.cat([x,y], dim=1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [ ]:
z=torch.stack([x,y])
print(z)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])


In [ ]:
print(z,"\n")
z=torch.stack([x,y], dim=0)
print(z,"\n")
z=torch.stack([x,y], dim=1)
print(z,"\n")
z=torch.stack([x,y], dim=2)
print(z)


#torch.stack([x, y], dim=0):
#x와 y를 첫 번째 차원(0번 축)을 기준으로 쌓아서 새로운 3차원 텐서 z를 만듭니다.

#torch.stack([x, y], dim=1):
#x와 y를 두 번째 차원(1번 축)을 기준으로 쌓아서 새로운 3차원 텐서 z를 만듭니다.

#torch.stack([x, y], dim=2):
#x와 y를 세 번째 차원(2번 축)을 기준으로 쌓아서 새로운 4차원 텐서 z를 만듭니다.

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]]) 

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]]) 

tensor([[[ 1.,  2.,  3.],
         [10., 11., 12.]],

        [[ 4.,  5.,  6.],
         [13., 14., 15.]],

        [[ 7.,  8.,  9.],
         [16., 17., 18.]]]) 

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])


In [ ]:
x= torch.FloatTensor([[[1,2]], [[3,4]]])
print(x)
print(x.size(),"\n\n\n")

y=x.expand(2,3,2)
print(y)
print(y.size())

tensor([[[1., 2.]],

        [[3., 4.]]])
torch.Size([2, 1, 2]) 



tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [ ]:
x=torch.randperm(10)
print(x)
print(x.size(),"\n\n\n")

x3=torch.randperm(3**3).view(3,3,-1)
print(x3)

tensor([0, 4, 7, 8, 5, 6, 2, 1, 9, 3])
torch.Size([10]) 



tensor([[[ 0, 15,  7],
         [24, 26, 18],
         [ 2,  6, 19]],

        [[13, 17,  3],
         [20, 12,  9],
         [14, 22, 16]],

        [[ 1,  5,  4],
         [23, 21,  8],
         [11, 25, 10]]])


In [ ]:
x3=torch.randperm(3**3).view(3,3,-1)
print(x3)
# y=x3.argmax(dim=-1)
# print(y)
# y=x3.argmax(dim=0)
# print(y)
# y=x3.argmax(dim=1)
# print(y)
y=x3.argmax(dim=2)
print(y)

#dim=0 =>z축
#dim=1 =>y축
#dim=2 =>x축

#y[0,0]-> 첫번째 차원에 1행에서 가장큰 값은 16이 나옴, 16의 위치는 0
#y[0,1]->첫번째 차원에 2행에서 가장큰 값은 26이 나옴, 26의 위치는 2
#y[0,3]->첫번째 차원에 2행에서 가장큰 값은 14이 나옴, 14의 위치는 0
#그래서 y의 첫번째 행이 [0,2,0]이됨

tensor([[[16, 13,  1],
         [22,  0, 26],
         [14, 10, 12]],

        [[ 5, 15, 17],
         [ 4, 18, 20],
         [11,  9,  2]],

        [[ 8,  6, 24],
         [ 3, 19, 25],
         [23,  7, 21]]])
tensor([[0, 2, 0],
        [2, 2, 0],
        [2, 2, 0]])
