In [2]:
import torch

In [4]:
torch.tensor([[1,2], [3,4]])

tensor([[1, 2],
        [3, 4]])

In [7]:
x=torch.FloatTensor([[1,2,3], [4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
print(torch.tensor([[1,2,],[3,4]]))
# print(torch.tensor([[1,2,],[3,4]]), device="cuda:0") #cuda tenser만드는것
print(torch.tensor([[1,2,],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [16]:
ft=torch.FloatTensor([[1,2,],[3,4]])
lt=torch.LongTensor([[1,2],[3,4]])
bt=torch.ByteTensor([[1,2],[3,4]]) #8bit로 작성되었단 결과가 나옴
print(ft)
print(lt)
print(bt)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [22]:
#nparray
import numpy as np

x=np.arange(0,9).reshape(3,3)
print(x, type(x))
x

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
#array->torch로 변환
tx=torch.from_numpy(x)
print(tx)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)


In [25]:
#torch->nparray
nx=tx.numpy()
print(nx, type(nx))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>
