- 배열(array): 데이터를 효율적으로 저장하고 다루기 위해 사용.\
 NumPy를 사용하여 배열을 생성하고, 배열 간의 연산이나 슬라이싱과 같은 다양한 작업을 수행할 수 있음.

- 텐서(Tensor): 주로 머신러닝과 딥러닝에서 데이터를 다루기 위해 사용.\
 딥러닝 모델은 주로 텐서를 입력으로 받고, 텐서를 출력으로 내보냄.\
  딥러닝 라이브러리인 파이토치와 텐서플로는 텐서를 생성하고, 뉴럴 네트워크의 학습과 예측 과정에서 텐서를 다루는 기능을 제공.

In [1]:
import torch

In [2]:
torch.tensor([[1,2], [3,4]])

tensor([[1, 2],
        [3, 4]])

In [3]:
x=torch.FloatTensor([[1,2,3], [4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
print(torch.tensor([[1,2,],[3,4]]))
# print(torch.tensor([[1,2,],[3,4]]), device="cuda:0") #cuda tenser만드는것
print(torch.tensor([[1,2,],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [5]:
ft=torch.FloatTensor([[1,2,],[3,4]])
lt=torch.LongTensor([[1,2],[3,4]])
bt=torch.ByteTensor([[1,2],[3,4]]) #8bit로 작성되었단 결과가 나옴
print(ft)
print(lt)
print(bt)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [6]:
#nparray
import numpy as np

x=np.arange(0,9).reshape(3,3)
print(x, type(x))
x

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#array->torch로 변환
tx=torch.from_numpy(x)
print(tx)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)


In [8]:
#torch->nparray
nx=tx.numpy()
print(nx, type(nx))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [9]:
tx #<- long형인데  float형으로, float형인데 long형으로
ft=tx.float()
print(ft)
lt= ft.long()
print(lt)
bt=ft.byte()
print(bt)


tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.uint8)


In [10]:
na=np.arange(1,13).reshape(2,3,2) #(z, y, x축)
na

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [11]:
t=torch.from_numpy(na)

In [12]:
print(t.size())  # 텐서의 크기를 출력합니다.

print(t.shape)  # 텐서의 모양(shape)을 튜플 형태로 출력합니다.

print(t.size(0))  # 텐서의 첫 번째 차원의 크기를 출력합니다.

print(t.shape[2])  # 텐서의 세 번째 차원의 크기를 출력합니다.

print(t.dim())  # 텐서의 차원 수를 출력합니다.

print(len(t.shape))  # 텐서의 차원 수를 출력합니다. t.dim()과 동일한 결과입니다.

print(t.size(-1))  # 텐서의 마지막 차원의 크기를 출력합니다.

print(t.shape[-1])  # 텐서의 마지막 차원의 크기를 출력합니다. t.size(-1)과 동일한 결과입니다.

torch.Size([2, 3, 2])
torch.Size([2, 3, 2])
2
2
3
3
2
2


In [13]:
a = torch.Tensor([[1, 2], [3, 4]])  # 2x2 크기의 텐서 a를 생성합니다.
b = torch.Tensor([[1, 2], [3, 4]])  # 2x2 크기의 텐서 b를 생성합니다.

print(a + b)  # 행렬 덧셈: 텐서 a와 b의 요소를 더하여 결과를 출력합니다.
print(a - b)  # 행렬 뺄셈: 텐서 a와 b의 요소를 빼서 결과를 출력합니다.
print(a * b)  # 요소별 곱셈: 텐서 a와 b의 요소를 곱하여 결과를 출력합니다.
print(a / b)  # 요소별 나눗셈: 텐서 a와 b의 요소를 나누어 결과를 출력합니다.
print(a == b)  # 요소별 비교 (같음): 텐서 a와 b의 요소가 같은지 비교하여 True 또는 False를 출력합니다.
print(a != b)  # 요소별 비교 (다름): 텐서 a와 b의 요소가 다른지 비교하여 True 또는 False를 출력합니다.
print(a ** b)  # 요소별 거듭제곱: 텐서 a의 요소를 텐서 b의 요소만큼 제곱하여 결과를 출력합니다.


tensor([[2., 4.],
        [6., 8.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[True, True],
        [True, True]])
tensor([[False, False],
        [False, False]])
tensor([[  1.,   4.],
        [ 27., 256.]])


In [14]:
print(a+1)
print(a-3)
print(a*2)
print(a/2)
print(a//2)  #// 연산자는 파이썬에서 사용되는 정수 나눗셈(나누기 연산의 몫을 계산)을 수행하는 연산자
print(a==2)
print(a>2)
print(a!=2)

tensor([[2., 3.],
        [4., 5.]])
tensor([[-2., -1.],
        [ 0.,  1.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[0., 1.],
        [1., 2.]])
tensor([[False,  True],
        [False, False]])
tensor([[False, False],
        [ True,  True]])
tensor([[ True, False],
        [ True,  True]])


In [15]:
c=torch.tensor([1,2])
print(a)
print(c)
print(a+c)


tensor([[1., 2.],
        [3., 4.]])
tensor([1, 2])
tensor([[2., 4.],
        [4., 6.]])


In [16]:
print(a)
print(b)
print(a*b) #<- 같은 행 열의 자리의값들끼리 곱함
print(a)
print(a.mul_(b)) # (= print(a*b)과 같은 기능이지만, a의 값이 변해버림
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


In [19]:
print(a)
print(a.sum())
print(a.sum(dim=0)) #열끼리 더하기
print(a.sum(dim=1)) #행끼리 더하기

tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor(30.)
tensor([10., 20.])
tensor([ 5., 25.])


In [29]:
t = np.arange(1, 13).reshape(3, 2, 2)  # 1부터 12까지의 숫자를 3x2x2 크기의 다차원 배열로 생성합니다. # (z, y, x축) 순서로 다차원 배열이 구성됩니다.
t = torch.from_numpy(t)  # NumPy 배열을 파이토치 텐서로 변환합니다.

print(t)  # 3차원 텐서를 출력합니다.
print(t.sum(dim=0))  # 첫 번째 축(z 축)을 따라 텐서의 합을 계산합니다.
print(t.sum(dim=1))  # 두 번째 축(y 축)을 따라 텐서의 합을 계산합니다.
print(t.sum(dim=2))  # 세 번째 축(x 축)을 따라 텐서의 합을 계산합니다.
print(t.sum(dim=-1))  # 마지막 축(x 축)을 따라 텐서의 합을 계산합니다.

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[15, 18],
        [21, 24]])
tensor([[ 4,  6],
        [12, 14],
        [20, 22]])
tensor([[ 3,  7],
        [11, 15],
        [19, 23]])
tensor([[ 3,  7],
        [11, 15],
        [19, 23]])


In [36]:
t=t.float()
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=2))
print(t.mean(dim=-1))



tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor(6.5000)
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])
