In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [4]:
torch.manual_seed(1)
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data = torch.FloatTensor([[3],[5],[7],[9],[11]])


In [5]:
model=nn.Linear(1,1) #선형회귀의 (input_dim=1, output_dim=1) / 입력크기1, 출력크기1
print(list(model.parameters())) # 초기값을 잡는것

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [6]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [7]:
nb_epochs=20000

for epoch in range(nb_epochs):
    prediction = model(x_data)
    cost = F.mse_loss(prediction, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('Epoch:', epoch, 'Cost:', cost.item())

Epoch: 0 Cost: 39.16685104370117
Epoch: 100 Cost: 0.08463062345981598
Epoch: 200 Cost: 0.04298952594399452
Epoch: 300 Cost: 0.021837208420038223
Epoch: 400 Cost: 0.01109258271753788
Epoch: 500 Cost: 0.00563468411564827
Epoch: 600 Cost: 0.0028622171375900507
Epoch: 700 Cost: 0.0014539161929860711
Epoch: 800 Cost: 0.0007385412463918328
Epoch: 900 Cost: 0.00037515218718908727
Epoch: 1000 Cost: 0.00019056595920119435
Epoch: 1100 Cost: 9.680409129941836e-05
Epoch: 1200 Cost: 4.91717473778408e-05
Epoch: 1300 Cost: 2.497919740562793e-05
Epoch: 1400 Cost: 1.2689983122982085e-05
Epoch: 1500 Cost: 6.447205578297144e-06
Epoch: 1600 Cost: 3.276181814726442e-06
Epoch: 1700 Cost: 1.6654261116855196e-06
Epoch: 1800 Cost: 8.460160643153358e-07
Epoch: 1900 Cost: 4.302897309571563e-07
Epoch: 2000 Cost: 2.1860606125301274e-07
Epoch: 2100 Cost: 1.1113379372318377e-07
Epoch: 2200 Cost: 5.657594925878584e-08
Epoch: 2300 Cost: 2.86554158179797e-08
Epoch: 2400 Cost: 1.4702209227834828e-08
Epoch: 2500 Cost: 7.

In [8]:
new_data=torch.FloatTensor([[10]])
y_pred=model(new_data)
print(y_pred)
print(list(model.parameters()))

tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [9]:
x_train=torch.FloatTensor( [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]])
y_train = torch.FloatTensor([[152.],[185.],[180.],[196.],[142.]])

model=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [10]:
optimizer=optim.SGD(model.parameters(), lr=1e-6)

In [11]:
nb_epochs=20000

for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('epoch:', epoch, '\n', 'Cost:', cost.item())
        print("Prameter:", list(model.parameters()), '\n')

epoch: 0 
 Cost: 42134.70703125
Prameter: [Parameter containing:
tensor([[-0.0769,  0.3060, -0.5081]], requires_grad=True), Parameter containing:
tensor([0.3467], requires_grad=True)] 

epoch: 400 
 Cost: 6.151466369628906
Prameter: [Parameter containing:
tensor([[0.6884, 1.0605, 0.2629]], requires_grad=True), Parameter containing:
tensor([0.3555], requires_grad=True)] 

epoch: 800 
 Cost: 6.023324012756348
Prameter: [Parameter containing:
tensor([[0.6928, 1.0550, 0.2641]], requires_grad=True), Parameter containing:
tensor([0.3556], requires_grad=True)] 

epoch: 1200 
 Cost: 5.89789342880249
Prameter: [Parameter containing:
tensor([[0.6971, 1.0495, 0.2653]], requires_grad=True), Parameter containing:
tensor([0.3556], requires_grad=True)] 

epoch: 1600 
 Cost: 5.775084495544434
Prameter: [Parameter containing:
tensor([[0.7013, 1.0440, 0.2665]], requires_grad=True), Parameter containing:
tensor([0.3556], requires_grad=True)] 

epoch: 2000 
 Cost: 5.655007839202881
Prameter: [Parameter co

In [12]:
print(list(model.parameters()))
new_data = torch.FloatTensor([[175, 80, 73]])
y_pred = model(new_data)
print(y_pred)

[Parameter containing:
tensor([[0.8539, 0.8476, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]
tensor([[240.2000]], grad_fn=<AddmmBackward0>)


In [13]:
torch.manual_seed(1)
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data = torch.FloatTensor([[3],[5],[7],[9],[11]])


In [14]:
#단순선형회귀(single regression)
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1) #단순선형회귀(입력각 출력각1)

    def forward(self, x):
        return self.linear(x)
    
model = LinearRegressionModel()
print(list(model.parameters()))
optimizer = optim.SGD(model.parameters(),lr=0.01)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [15]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_data)
    cost=F.mse_loss(prediction,t_data)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400 == 0:
        print('Epoch:', epoch, 'Cost:', 'cost.item()')


Epoch: 0 Cost: cost.item()


Epoch: 400 Cost: cost.item()
Epoch: 800 Cost: cost.item()
Epoch: 1200 Cost: cost.item()
Epoch: 1600 Cost: cost.item()
Epoch: 2000 Cost: cost.item()
Epoch: 2400 Cost: cost.item()
Epoch: 2800 Cost: cost.item()
Epoch: 3200 Cost: cost.item()
Epoch: 3600 Cost: cost.item()
Epoch: 4000 Cost: cost.item()
Epoch: 4400 Cost: cost.item()
Epoch: 4800 Cost: cost.item()
Epoch: 5200 Cost: cost.item()
Epoch: 5600 Cost: cost.item()
Epoch: 6000 Cost: cost.item()
Epoch: 6400 Cost: cost.item()
Epoch: 6800 Cost: cost.item()
Epoch: 7200 Cost: cost.item()
Epoch: 7600 Cost: cost.item()
Epoch: 8000 Cost: cost.item()
Epoch: 8400 Cost: cost.item()
Epoch: 8800 Cost: cost.item()
Epoch: 9200 Cost: cost.item()
Epoch: 9600 Cost: cost.item()
Epoch: 10000 Cost: cost.item()
Epoch: 10400 Cost: cost.item()
Epoch: 10800 Cost: cost.item()
Epoch: 11200 Cost: cost.item()
Epoch: 11600 Cost: cost.item()
Epoch: 12000 Cost: cost.item()
Epoch: 12400 Cost: cost.item()
Epoch: 12800 Cost: cost.item()
Epoch: 13200 Cost: cost.item()
Epo

In [16]:
#다중선형회귀
new_data = torch.FloatTensor([[10]])
pred_y= model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [17]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [18]:
model=MultiLinearRegressionModel()
optimizer=optim.SGD(model.parameters(), lr=1e-6)

In [19]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('Epoch', epoch, 'Cost:', cost.item())

Epoch 0 Cost: 42134.70703125


Epoch 400 Cost: 6.151466369628906
Epoch 800 Cost: 6.023324012756348
Epoch 1200 Cost: 5.89789342880249
Epoch 1600 Cost: 5.775084495544434
Epoch 2000 Cost: 5.655007839202881
Epoch 2400 Cost: 5.537505149841309
Epoch 2800 Cost: 5.4224958419799805
Epoch 3200 Cost: 5.309939384460449
Epoch 3600 Cost: 5.199779033660889
Epoch 4000 Cost: 5.091987609863281
Epoch 4400 Cost: 4.986566066741943
Epoch 4800 Cost: 4.8833770751953125
Epoch 5200 Cost: 4.782319068908691
Epoch 5600 Cost: 4.68351936340332
Epoch 6000 Cost: 4.586774826049805
Epoch 6400 Cost: 4.492152214050293
Epoch 6800 Cost: 4.399523735046387
Epoch 7200 Cost: 4.308913707733154
Epoch 7600 Cost: 4.220221519470215
Epoch 8000 Cost: 4.1334333419799805
Epoch 8400 Cost: 4.048529148101807
Epoch 8800 Cost: 3.9653878211975098
Epoch 9200 Cost: 3.88407564163208
Epoch 9600 Cost: 3.8044819831848145
Epoch 10000 Cost: 3.7265963554382324
Epoch 10400 Cost: 3.6503875255584717
Epoch 10800 Cost: 3.5758132934570312
Epoch 11200 Cost: 3.5028367042541504
Epoch 11600 

In [20]:
new_data=torch.FloatTensor([[80,90,75]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[168.1732]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.8539, 0.8476, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


-------------------------------------------------------------------------

In [21]:
data=np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype='float32')
x_data = data[:, 0:-1]
t_data = data[:,[-1]]
# print(x_data[:5])
# print(t_data[:5])

x_train=torch.from_numpy(x_data)
t_train=torch.from_numpy(t_data)
print(x_train[:5])
print(t_train[:5])


tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [22]:
model1= nn.Linear(3,1)
print(list(model1.parameters()))


[Parameter containing:
tensor([[-0.1188,  0.2937,  0.0803]], requires_grad=True), Parameter containing:
tensor([-0.0707], requires_grad=True)]


In [23]:
optimizer=optim.SGD(model1.parameters(), lr=1e-6)

In [27]:
nb_epochs = 520000

for epoch in range(nb_epochs):
    prediction = model1(x_train)
    cost = F.mse_loss(prediction, t_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%400==0:
        print('epoch:', epoch, '\n', 'Cost:', cost.item())
        # print("Prameter:", list(model1.parameters()), '\n')


epoch: 0 
 Cost: 6.086429595947266
epoch: 400 
 Cost: 6.086417198181152
epoch: 800 
 Cost: 6.086408615112305
epoch: 1200 
 Cost: 6.086400032043457
epoch: 1600 
 Cost: 6.086391448974609
epoch: 2000 
 Cost: 6.086370944976807
epoch: 2400 
 Cost: 6.086362361907959
epoch: 2800 
 Cost: 6.086346626281738
epoch: 3200 
 Cost: 6.086342811584473
epoch: 3600 
 Cost: 6.086321830749512
epoch: 4000 
 Cost: 6.0863037109375
epoch: 4400 
 Cost: 6.086303234100342
epoch: 4800 
 Cost: 6.086277008056641
epoch: 5200 
 Cost: 6.086264133453369
epoch: 5600 
 Cost: 6.086269378662109
epoch: 6000 
 Cost: 6.086238861083984
epoch: 6400 
 Cost: 6.086236476898193
epoch: 6800 
 Cost: 6.0862274169921875
epoch: 7200 
 Cost: 6.086224555969238
epoch: 7600 
 Cost: 6.086201190948486
epoch: 8000 
 Cost: 6.086191177368164
epoch: 8400 
 Cost: 6.086180210113525
epoch: 8800 
 Cost: 6.086164951324463
epoch: 9200 
 Cost: 6.086142539978027
epoch: 9600 
 Cost: 6.086138725280762
epoch: 10000 
 Cost: 6.086127758026123
epoch: 10400 
 Co

In [28]:
class MultiLinearRegressModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear==nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = MultiLinearRegressionModel
optimizer = optim.SGD(model.parameters(), lr=1e-6)
nb_epochs = 2000000
for epoch in range(nb_epochs):
    prediction = model(x_train)
    cost=F.mse_loss(prediction, t_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%1000==0
        print('epoch:', epoch, '\n', 'Cost:', cost.item())
